package transcript

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestPinsMatchLocalUIBuild guards the coupling between the two libraries from
// the Go side: the pinned version, CDN URLs and SRI hashes in pins.go are
// derived from discord-transcript-ui's build output, and they go stale the
// moment it is rebuilt (the version is baked into every artifact's banner, so
// the hashes change too).
//
// The JS build rewrites pins.go automatically; this test catches the cases it
// cannot: a hand edit, or a rebuild with the Go module checked out somewhere the
// build could not see. It skips when the UI repository is not next to this
// module, so the package still tests standalone.
func TestPinsMatchLocalUIBuild(t *testing.T) {
	path := filepath.Join("..", "..", "dist", "manifest.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Skip("discord-transcript-ui is not checked out next to this module")
	}

	var manifest struct {
		Version   string                       `json:"version"`
		URLs      map[string]map[string]string `json:"urls"`
		Integrity map[string]string            `json:"integrity"`
	}
	if err := json.Unmarshal(data, &manifest); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}

	if manifest.Version != ContractVersion {
		t.Errorf("ContractVersion is %q but the UI build is %q; run `npm run build` in discord-transcript-ui",
			ContractVersion, manifest.Version)
	}

	checks := []struct {
		name string
		got  string
		want string
	}{
		{"DefaultCSSURL", DefaultCSSURL, manifest.URLs["css"]["jsdelivr"]},
		{"DefaultCSSIntegrity", DefaultCSSIntegrity, manifest.Integrity["css"]},
		{"DefaultShortCSSURL", DefaultShortCSSURL, manifest.URLs["cssShort"]["jsdelivr"]},
		{"DefaultShortCSSIntegrity", DefaultShortCSSIntegrity, manifest.Integrity["cssShort"]},
		{"DefaultScriptURL", DefaultScriptURL, manifest.URLs["js"]["jsdelivr"]},
		{"DefaultScriptIntegrity", DefaultScriptIntegrity, manifest.Integrity["js"]},
	}
	for _, check := range checks {
		if check.got != check.want {
			t.Errorf("%s is out of date:\n  got  %q\n  want %q\nrun `npm run build` in discord-transcript-ui to regenerate pins.go",
				check.name, check.got, check.want)
		}
	}
}

// TestGeneratedFilesAreMarkedGenerated makes it obvious where the pinned values
// come from, so nobody edits them by hand and silently loses the change.
func TestGeneratedFilesAreMarkedGenerated(t *testing.T) {
	for _, name := range []string{"pins.go", "tags_gen.go"} {
		data, err := os.ReadFile(name)
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		if !strings.Contains(string(data), "Code generated by build/sync-go.mjs") {
			t.Errorf("%s should carry the generated-code header", name)
		}
	}
}
