// Code generated by build/sync-go.mjs from build/short-tags.mjs.
// DO NOT EDIT: run `npm run build` in discord-transcript-ui to refresh.

package transcript

// shortTagNames maps each semantic element name to its compact tag. Keep this in
// step by rebuilding discord-transcript-ui, which regenerates this file.
var shortTagNames = map[string]string{
	"action-row":          "dar",
	"attachments":         "dats",
	"audio-attachment":    "daud",
	"author-info":         "dai",
	"bold":                "db",
	"button":              "dbtn",
	"code":                "dc",
	"command":             "dcmd",
	"custom-emoji":        "demo",
	"embed":               "de",
	"embed-description":   "ded",
	"embed-field":         "def",
	"embed-fields":        "defs",
	"embed-footer":        "defo",
	"file-attachment":     "dfil",
	"header":              "dh",
	"image-attachment":    "dimg",
	"italic":              "di",
	"link":                "dl",
	"list-item":           "dli",
	"mention":             "dme",
	"message":             "dm",
	"messages":            "dms",
	"ordered-list":        "dol",
	"pre":                 "dp",
	"quote":               "dq",
	"reaction":            "dr",
	"reactions":           "drs",
	"reply":               "drp",
	"spoiler":             "dsp",
	"strikethrough":       "dst",
	"subscript":           "dsub",
	"system-message":      "dsy",
	"thread":              "dth",
	"thread-message":      "dthm",
	"time":                "dti",
	"underlined":          "dun",
	"unordered-list":      "dul",
	"verified-author-tag": "dvat",
	"video-attachment":    "dvid",
}
