package transcript

import (
	"regexp"
	"strings"
)

// The compact tag vocabulary (WithShortTags) lives in tags_gen.go, generated by
// discord-transcript-ui's build so the two repositories cannot drift. It is a
// straight rename of the readable default names, which is why the short
// stylesheet is the same size as the default one.
//
// Measured on a text-heavy transcript, short codes cut ~21% of the raw markup
// and ~5% of the gzipped markup: repeated long names compress well, so the win
// matters for uncompressed files on disk.
// tagPattern matches an opening or closing tag name in the generated markup.
//
// This is safe to run over a finished fragment: message content is HTML-escaped
// before it is written, so a literal "<discord-" in the output can only be a tag
// this package emitted. User text that mentioned a tag arrives as
// "&lt;discord-...&gt;" and is not matched.
var tagPattern = regexp.MustCompile(`</?(discord-[a-z-]+)`)

// shortenTags rewrites every tag name in a rendered fragment to its short code.
func shortenTags(fragment string) string {
	return tagPattern.ReplaceAllStringFunc(fragment, func(match string) string {
		prefix, name := "<", match[1:]
		if strings.HasPrefix(match, "</") {
			prefix, name = "</", match[2:]
		}
		if short, ok := shortTagNames[strings.TrimPrefix(name, "discord-")]; ok {
			return prefix + short
		}
		return match
	})
}

// ShortTags returns the compact tag vocabulary, keyed by the semantic element
// name (the part after "discord-"). It is a copy, so callers cannot corrupt the
// renderer's mapping.
func ShortTags() map[string]string {
	out := make(map[string]string, len(shortTagNames))
	for name, short := range shortTagNames {
		out[name] = short
	}
	return out
}
